name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update stats
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/update \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.UPDATE_STATS_SECRET }}" \
          -d '{}'
