name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # runs at midnight UTC daily
  workflow_dispatch: # allows manual trigger too

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: trigger stats update
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}/api/stats/update \
          -H "Authorization: Bearer ${{ secrets.UPDATE_STATS_SECRET }}"
